---
__setup_devserver_devusers:
  - name: user1
    team: network
    password: Password1
  - name: user2
    team: network
    password: Password1
  - name: user3
    team: wintel
    password: Password1
__setup_devserver_teams:
  - name: network
    whitelist:
      - 192.168.10.1
      - 192.168.10.2
  - name: wintel
    whitelist: 
      - 192.168.20.1
      - 192.168.20.2
__setup_devserver_devcontainer: registry.redhat.io/ansible-automation-platform-25/ansible-dev-tools-rhel8:latest