---
- name: Configure podmansh
  ansible.builtin.template:
    src: templates/podmansh.container
    dest: /etc/containers/systemd/podmansh.container
    owner: root
    group: root
    mode: '0644'
  vars:
    devcontainer: "{{ __setup_devserver_devcontainer }}"

- name: Create groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: present
  loop:
    "{{ __setup_devserver_teams }}"

- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.team }}"
    append: true
    shell: "/usr/bin/podmansh"
    password: "{{ item.password | password_hash('sha512', 'dummysalt') }}"
  loop:
    "{{ __setup_devserver_devusers }}"

- name: Get all the group details
  ansible.builtin.getent:
    database: group
    split: ':'
  register: __setup_devserver_group_lookup

- name: Extract the group list from the lookup
  ansible.builtin.set_fact:
    __setup_devserver_group_lookup: "{{ __setup_devserver_group_lookup.ansible_facts.getent_group }}"

- name: Add nftables config
  ansible.builtin.template:
    src: templates/group_whitelist.nft
    dest: "/etc/nftables/group_{{ item.name }}_whitelist.nft"
    owner: root
    group: root
    mode: '0644'
  vars:
    whitelist_ips: "{{ item.whitelist | join(',') }}"
    whitelist_gid: "{{ __setup_devserver_group_lookup[item.name][1] }}"
  loop:
    "{{ __setup_devserver_teams }}"

- name: Restart nftables
  ansible.builtin.systemd:
    name: nftables
    state: restarted
    enabled: true
